name: 'My Adding Action'
description: 'This action will demonstrate how GH Actions work'

inputs:
  first_number:
    descrption: 'Enter your first number:'
    required: true
  second_number:
    descrption: 'Enter your second number:'
    required: true

outpus:
  SUM:
    description: 'The sum of the numbers'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.first_number }}
    - ${{ inputs.second_number }}
