name: MyPushWorkflow
on:
  push:
    branches:
      - master

jobs:
  my-job:
    runs-on: ubuntu-20.04
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: my-second-step
        run: echo "Hello to engineers on Bank On tech!"

  my-second-job:
    needs: [my-job]
    environment:
      name: Demo
    runs-on: ubuntu-20.04
    steps:
      - name: my-step
        run: echo "Here is my secret ${{ secrets.MY_SECRET}}"
